### ISSUE TITLE
如何进行部署在服务器上？

### ISSUE THREAD

**Issue by lmuiotctf** [bestruirui/ChatGPT-Web#1]
请问如何进行部署在服务器上？

**Comment by bestruirui** [comment]
运行server
修改client/scripts.js 112行api地址

**Comment by lmuiotctf** [comment]
可以协助下嘛。直接npm i  npm run server 嘛
应该是运行client前端项目吧

**Comment by bestruirui** [comment]
进入各自对应的文件夹，先运行后端，然后修改前端的api地址，编译前端

**Comment by lmuiotctf** [comment]
![image](https://user-images.githubusercontent.com/52068443/217179762-e37ced8e-333c-4b01-a147-bddad7825413.png)
目前已经部署在vercel 但是无法访问，我本地调式 npm i 会卡住
![image](https://user-images.githubusercontent.com/52068443/217180085-f507626a-ed0d-4e80-96c6-aad0d693254b.png)

**Comment by bestruirui** [comment]
![image](https://user-images.githubusercontent.com/89796393/217181835-070aeed8-76ce-45a5-9313-17829059bb16.png)

**Comment by bestruirui** [comment]
![image](https://user-images.githubusercontent.com/89796393/217182092-65114347-5ba2-4aaa-9044-b2b8ebb082d9.png)

**Comment by lmuiotctf** [comment]
奇怪了，我这边npm i 卡住

**Comment by lmuiotctf** [comment]
![image](https://user-images.githubusercontent.com/52068443/217182851-5052bfee-b0a5-4f9f-8f8b-ea2e9e0d1066.png)

**Comment by bestruirui** [comment]
![image](https://user-images.githubusercontent.com/89796393/217184090-b2670b27-0454-49ab-ad44-253d075cd2a0.png)

**Comment by lmuiotctf** [comment]
哈哈哈 我版本不是你这个 比你的低

**Comment by lmuiotctf** [comment]
可以帮忙打包下嘛🐧🐧

**Comment by bestruirui** [comment]
用Github的codespace就可以

**Comment by lmuiotctf** [comment]
server是可以 client npm install 卡住🕊️

**Comment by lmuiotctf** [comment]
openai 的key值要填在哪里
