### ISSUE TITLE
api的key需要在哪里替换，readme中没有提到耶

### ISSUE THREAD

**Issue by lmuiotctf** [bestruirui/ChatGPT-Web#2]
api的key需要在哪里替换，readme中没有提到
目前项目运行起来了，就是key没说哪里替换

**Comment by bestruirui** [comment]
稍微看一下代码就知道了啊
![image](https://user-images.githubusercontent.com/89796393/217241608-e88cf672-0a69-4220-b5c4-44e9bf5e3111.png)
